import { StyleSheet } from 'react-native';

export const trackingStyle = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0A1810', // Dark green background
  },
  header: {
    backgroundColor: '#1A2F23', // Darker green header
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#1E884F',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#E2F5EA', // Light green text
  },
  dateNavigation: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  dateButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#0D1E13',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#1E884F',
    shadowColor: '#117041',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 3,
    elevation: 5,
  },
  dateText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#E2F5EA',
  },
  summaryCard: {
    borderRadius: 12,
    margin: 15,
    shadowColor: '#117041',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 8,
    borderWidth: 1,
    borderColor: '#1E884F',
    overflow: 'hidden',
    backgroundColor: '#0D1E13',
  },
  cardContent: {
    padding: 15,
    borderRadius: 12,
  },
  summaryTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#E2F5EA',
    marginBottom: 15,
  },
  macrosSummary: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  macroItem: {
    flex: 1,
    alignItems: 'center',
  },
  macroValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#4CD471', // Bright green for values
  },
  macroLabel: {
    fontSize: 12,
    color: '#A3E2B8', // Lighter green
    marginVertical: 4,
  },
  macroGoal: {
    fontSize: 11,
    color: '#6BAF80', // Medium green
  },
  macroDivider: {
    width: 1,
    height: '100%',
    backgroundColor: '#1E884F',
  },
  waterCard: {
    borderRadius: 12,
    margin: 15,
    marginTop: 0,
    shadowColor: '#117041',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 8,
    borderWidth: 1,
    borderColor: '#1E884F',
    overflow: 'hidden',
    backgroundColor: '#0D1E13',
  },
  waterTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#E2F5EA',
    marginBottom: 15,
    alignSelf: 'flex-start',
  },
  waterTracker: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: 10,
  },
  waterButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(30, 136, 79, 0.2)',
  },
  waterGlasses: {
    flexDirection: 'row',
    justifyContent: 'center',
    flexWrap: 'wrap',
    flex: 1,
    paddingHorizontal: 20,
  },
  waterStatus: {
    fontSize: 14,
    color: '#A3E2B8',
    marginTop: 10,
    textAlign: 'center',
  },
  mealsSection: {
    margin: 15,
    marginTop: 0,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#E2F5EA',
    marginBottom: 15,
  },
  mealCard: {
    borderRadius: 12,
    marginBottom: 15,
    shadowColor: '#117041',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 8,
    borderWidth: 1,
    borderColor: '#1E884F',
    overflow: 'hidden',
    backgroundColor: '#0D1E13',
  },
  mealCardPressed: {
    transform: [{ scale: 0.98 }],
    opacity: 0.9,
  },
  mealCardContent: {
    padding: 15,
    borderRadius: 12,
  },
  mealHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  mealType: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#E2F5EA',
  },
  mealTime: {
    fontSize: 12,
    color: '#A3E2B8',
    marginTop: 4,
  },
  mealCalories: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#4CD471',
  },
  mealItems: {
    borderTopWidth: 1,
    borderTopColor: '#1E884F',
    paddingTop: 10,
  },
  foodItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
  },
  foodName: {
    fontSize: 14,
    color: '#E2F5EA',
  },
  foodCalories: {
    fontSize: 14,
    color: '#A3E2B8',
  },
  emptyMeal: {
    padding: 15,
    alignItems: 'center',
  },
  emptyText: {
    fontSize: 14,
    color: '#6BAF80',
    marginBottom: 12,
  },
  addButton: {
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: '#117041',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 3,
    elevation: 5,
  },
  addButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: '#117041',
  },
  addButtonText: {
    fontSize: 14,
    color: '#E2F5EA',
    marginLeft: 4,
    fontWeight: '500',
  },
  addMoreButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#1E884F',
  },
  addMoreText: {
    fontSize: 14,
    color: '#4CD471',
    marginLeft: 4,
    fontWeight: '500',
  },
  addMealButton: {
    margin: 15,
    marginTop: 0,
    marginBottom: 30,
    borderRadius: 25,
    shadowColor: '#117041',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 8,
    overflow: 'hidden',
  },
  addMealContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    borderRadius: 25,
    backgroundColor: '#117041',
  },
  addMealButtonText: {
    color: 'white',
    fontWeight: 'bold',
    marginLeft: 8,
    fontSize: 16,
  },
});