import { StyleSheet } from 'react-native';

export const dashboardStyles =StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 15,
  },
  greeting: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#333333',
  },
  date: {
    fontSize: 16,
    color: '#666666',
    marginTop: 5,
  },
  caloriesCard: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 15,
    marginHorizontal: 20,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333333',
    marginBottom: 15,
  },
  caloriesContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  caloriesChart: {
    position: 'relative',
    width: 140,
    height: 140,
    alignItems: 'center',
    justifyContent: 'center',
  },
  caloriesChartLabel: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  caloriesConsumed: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333333',
  },
  caloriesUnit: {
    fontSize: 14,
    color: '#666666',
  },
  caloriesSummary: {
    flex: 1,
    marginLeft: 20,
  },
  caloriesItem: {
    marginBottom: 15,
  },
  caloriesItemLabel: {
    fontSize: 14,
    color: '#666666',
    marginBottom: 5,
  },
  caloriesItemValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333333',
  },
  macrosCard: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 15,
    marginHorizontal: 20,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 2,
  },
  macroContent: {
    marginTop: 5,
  },
  macroItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  macroIconContainer: {
    width: 30,
    alignItems: 'center',
  },
  macroIcon: {
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  macroDetail: {
    flex: 1,
    marginLeft: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  macroTitle: {
    width: 70,
    fontSize: 16,
    color: '#333333',
  },
  macroProgressContainer: {
    flex: 1,
    height: 8,
    backgroundColor: '#E0E0E0',
    borderRadius: 4,
    marginRight: 10,
  },
  macroProgress: {
    height: 8,
    borderRadius: 4,
  },
  macroPercentage: {
    width: 40,
    fontSize: 14,
    color: '#333333',
    fontWeight: 'bold',
  },
  quickActionsCard: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 15,
    marginHorizontal: 20,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 2,
  },
  quickActionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  quickActionItem: {
    width: '48%',
    backgroundColor: '#F8F9FA',
    borderRadius: 10,
    padding: 15,
    marginBottom: 15,
    alignItems: 'center',
  },
  quickActionIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#399AA8',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  quickActionTitle: {
    fontSize: 14,
    color: '#333333',
    textAlign: 'center',
  },
  alertsCard: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 15,
    marginHorizontal: 20,
    marginBottom: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 2,
  },
  alertsList: {
    marginTop: 5,
  },
  alertItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    backgroundColor: '#F8F9FA',
    borderRadius: 10,
    padding: 12,
  },
  alertIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  alertContent: {
    flex: 1,
  },
  alertTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333333',
    marginBottom: 5,
  },
  alertDescription: {
    fontSize: 14,
    color: '#666666',
  },
});
